feat(canoctl): Tell people that SELinux is unsupported, but don't disable it ourselves
Changing such a setting behind someone's back is a bit rude…

diff --git a/sources/canopsis/scripts/canoctl b/sources/canopsis/scripts/canoctl
--- a/sources/canopsis/scripts/canoctl
+++ b/sources/canopsis/scripts/canoctl
@@ -28,6 +28,13 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 1
 fi
 
+if command -v selinuxenabled >/dev/null 2>&1 && selinuxenabled ; then
+	echo "ERROR: Running Canopsis with SELinux is unsupported."
+	echo "Please disable it, if you may."
+
+	exit 1
+fi
+
 while true ; do
 	case $1 in
 	start|status|restart|stop)
